### ISSUE TITLE
Can´t run PanelPi

### ISSUE THREAD

**Issue by Tekkineo** [patrickkuo/PanelPi#7]
Hello,
I did everything like in the instructions. but in step 10 I fail. 
I got the message: "Error: Unable to access jarfile panelPi.jar"
My mainproblem is that when I download the file from github I get a Zip-file (I´m using windows and copy the file to the rasperry via remote). So I didn´t have any jar-file even when I Unzip the package from github.
How do I get the jar-file? I´m a little helpless :(

**Comment by patrickkuo** [comment]
<img width="1030" alt="Screenshot 2019-08-16 at 9 45 53 AM" src="https://user-images.githubusercontent.com/1888654/63137966-0d310380-c00b-11e9-806d-808575991287.png">
